import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";

import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "../globals.css";
import { ReactNode } from "react";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "4Tek",
  description: "Generated by create next app",
};

interface LayoutProps {
  children: ReactNode;
  params: any;
}

export default async function LocaleLayout({ children, params }: LayoutProps) {
  const { locale } = params;

  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={montserrat.variable}>
        <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
